files:
  include: '**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: false
rules:
  border-zero: 1
  empty-line-between-blocks:
    - 1
    - ignore-single-line-rulesets: true
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline:
    - 1
    - include: true
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 1
  function-name-format:
    - 1
    - convention: hyphenatedlowercase
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  indentation:
    - 1
    - size: 4
  leading-zero:
    - 1
    - include: false
  mixin-name-format:
    - 1
    - convention: hyphenatedlowercase
  mixins-before-declarations: 1
  nesting-depth:
    - 1
    - max-depth: 10
  no-color-literals: 0
  no-css-comments: 1
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-ids: 0
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties:
    - 1
    - extra-properties: []
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: true
  no-url-protocols: 1
  placeholder-in-extend: 0
  placeholder-name-format:
    - 1
    - convention: hyphenatedlowercase
  property-sort-order:
    - 1
    - order: concentric
  quotes:
    - 1
    - style: single
  shorthand-values: 1
  single-line-per-selector: 1
  space-after-colon: 1
  space-after-comma: 1
  space-before-brace: 1
  space-before-colon: 1
  space-between-parens:
    - 1
    - include: false
  url-quotes: 1
  variable-name-format:
    - 1
    - convention: hyphenatedlowercase
  zero-unit: 1
